regions:
- global
- eu-west-1
- eu-west-2
- eu-west-3
- eu-central-1
#- eu-north-1
#- us-east-1
#- us-east-2
#- us-west-1
#- us-west-2
#- ap-northeast-1
#- ap-northeast-2
#- ap-northeast-3
#- ap-south-1
#- ap-southeast-1
#- ap-southeast-2
#- ca-central-1
#- sa-east-1

account-blacklist:
- "123456789012" # add at least one account

accounts:
  "||ACCOUNT||":
    filters:
      IAMRole:
      - "Administrator"
      IAMRolePolicy:
      - "Administrator -> AdministratorAccess"
      IAMRolePolicyAttachment:
      - "Administrator -> AdministratorAccess"

