---
AWSTemplateFormatVersion: '2010-09-09'
Description: Stack providing cross account access for Hitman
# Suggested StackName : hitman-spoke-account

Parameters:

  HitmanCentralAccount:
    Description: AWS accountID where Hitman is installed
    Type: String
    ConstraintDescription: Must be a valid AWS account ID
    
  HitmanNukeAssumeRoleExternalId:
    Description: Hitman Role External ID
    Type: String

Resources:

  HitmanNukeAssumeRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: hitman-nuke-role
      MaxSessionDuration: 3600
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            AWS: !Sub 'arn:aws:iam::${HitmanCentralAccount}:root'
          Action:
          - sts:AssumeRole
          Condition:
            StringEquals:
              "sts:ExternalId": !Sub '${HitmanNukeAssumeRoleExternalId}'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      Path: "/"
