AWSTemplateFormatVersion: '2010-09-09'
Description: Common resources for Hitman
# Stack Name : hitman-common
# Description : this stack creates the Hitman main stack prerequisites :
# - one ECR repository
# - one S3 bucket


Parameters:

  DisplayName:
    Description: Baseline for naming ressources
    Type: String

  TagBlock:
    Description: Applicative block tag
    Type: String

  TagApp:
    Description: Application referenced by this stack
    Type: String

  TagOrg:
    Description: Organization Unit
    Type: String

  HitmanEcrRepoName:
    Description: Organization Unit
    Type: String


Resources:

  HitmanEcrRepository:
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: !Sub '${HitmanEcrRepoName}'

  HitmanS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${DisplayName}-conf-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      Tags:
      - Key: Block
        Value: !Sub '${TagBlock}'
      - Key: App
        Value: !Sub '${TagApp}'
      - Key: Org
        Value: !Sub '${TagOrg}'

Outputs:

  HitmanEcrRepository:
    Description: Hitman ECR repository
    Value: !GetAtt HitmanEcrRepository.Arn
    Export:
      Name: !Sub "${AWS::StackName}-EcrRepository"

  HitmanS3Bucket:
    Description: Hitman S3 bucket
    Value: !GetAtt HitmanS3Bucket.Arn
    Export:
      Name: !Sub "${AWS::StackName}-S3Bucket"

