AWSTemplateFormatVersion: '2010-09-09'
Description: Common resources for Hitman
# Stack Name : hitman-common
# Description : this stack creates the Hitman main stack prerequisites :
# - one ECR repository
# - one S3 bucket

Parameters:

  TagBlock:
    Description: Applicative block tag
    Type: String
    Default: sharedservices

  TagApp:
    Description: Application referenced by this stack
    Type: String
    Default: prowler

  TagOrg:
    Description: Organization Unit
    Type: String
    Default: cloudteam

  HitmanEcrRepoName:
    Description: Organization Unit
    Type: String
    Default: prowler

Resources:

  HitmanEcrRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref HitmanEcrRepoName
      Tags:
      - Key: Block
        Value: !Ref TagBlock
      - Key: App
        Value: !Ref TagApp
      - Key: Org
        Value: !Ref TagOrg

  HitmanS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${TagApp}-conf-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      Tags:
      - Key: Block
        Value: !Ref TagBlock
      - Key: App
        Value: !Ref TagApp
      - Key: Org
        Value: !Ref TagOrg

Outputs:

  HitmanEcrRepository:
    Description: Hitman ECR repository
    Value: !GetAtt HitmanEcrRepository.Arn
    Export:
      Name: !Sub "${AWS::StackName}-EcrRepository"

  HitmanS3Bucket:
    Description: Hitman S3 bucket
    Value: !GetAtt HitmanS3Bucket.Arn
    Export:
      Name: !Sub "${AWS::StackName}-S3Bucket"
